### PR TITLE
Consolidate connection handling code

### PR DESCRIPTION
**Pull request by bf4**
Extracted from #67

### CODE REVIEW

**Comment by ntippie** [comment]
Not directly related to this refactoring, but I think we should make `#attachment_connection` a public method to match `#connection`.

**Comment by minimul** [comment]
@ntippie Yep, sounds good.

**Comment by bf4** [comment]
@ntippie @minimul made public

**Comment by minimul** [comment]
This one is ready to be merged after the conflict is resolved.

**Comment by bf4** [comment]
rebased and force pushed. reviewing to see if I made any mistakes in the conflict resolution

**Comment by bf4** [comment]
looks good to me

**Comment by minimul** [comment]
Thanks!

**Pull request merged**
