### PR TITLE
Add attachment read/delete methods

### LINKED ISSUE #103: Support other actions on attachables
Looks like this package only supports uploading attachments for now. Would be great to support the other endpoints: https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/attachable.

In particular, supporting deleting attachments would be very useful for our use case.

### PR DESCRIPTION
**Pull request by franklin-stripe**
* Add `read` and `delete` methods on attachments (along with tests)

Fixes #103

### CODE REVIEW

**Comment by franklin-stripe** [comment]
This is having some build errors that should be fixed in https://github.com/minimul/qbo_api/pull/105

**Comment by minimul** [comment]
Thanks – well done.

Can you run again on the CI with `>= 1.10` being passed to the bundler gem dependency?

**Comment by franklin-stripe** [comment]
@minimul added a commit with the bundler gem dependency and things seem to work

**Comment by minimul** [comment]
Ok, I took a closer look.

Take out the bump version to 1.8.6 commit and then squash all commits into a single commit with a good description.

Thanks.

**Comment by franklin-stripe** [comment]
@minimul done!

**Comment by minimul** [comment]
Thanks again @franklin-stripe – released as 1.8.6

**Pull request merged**
